.Dd January 31, 2014
.Dt msiecfinfo
.Os libmsiecf
.Sh NAME
.Nm msiecfinfo
.Nd determines information about a MSIE Cache File (index.dat)
.Sh SYNOPSIS
.Nm msiecfinfo
.Op Fl c Ar codepage
.Op Fl ahvV
.Va Ar source
.Sh DESCRIPTION
.Nm msiecfinfo
is a utility to determine information about a MSIE Cache File (index.dat)
.Pp
.Nm msiecfinfo
is part of the
.Nm libmsiecf
package.
.Nm libmsiecf
is a library to access the MSIE Cache File (index.dat) format.
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
shows allocation information
.It Fl c Ar codepage
specify the codepage of ASCII strings, options: ascii, windows-874, windows-932, windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252 (default), windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 or windows-1258
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# msiecfinfo -a index.dat
msiecfinfo 20100917

MSIE Cache File information:
	File size:			32768 bytes
	Number of items:		42
	Number of recovered items:	0

Unallocated data blocks:
	00031232 (0x00007a00) - 00032768 (0x00008000) size: 1536

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libmsiecf
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2009-2020, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr msiecfexport 1
.Xr msiecfrecover 1
